title: AI Upscaler Plugin
description: Professional AI upscaling with AV1 hardware acceleration for Jellyfin
theme: minima
github:
  repository_url: https://github.com/Kuschel-code/JellyfinUpscalerPlugin
  
plugins:
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-feed
  
markdown: kramdown
highlighter: rouge

navigation:
  - title: Home
    url: /
  - title: Installation
    url: /docs/Installation-Guide
  - title: Hardware Support
    url: /docs/Hardware-Compatibility
  - title: Quick Settings
    url: /docs/Quick-Settings-UI
  - title: API Reference
    url: /docs/API-Reference