# CasaOS-optimized Docker Compose for Jellyfin AI Upscaler Plugin
# Supports ARM64, Raspberry Pi, and Zimaboard

version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin-ai-upscaler
    environment:
      # CasaOS-specific user/group IDs
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # Docker platform specification for ARM64
      - DOCKER_DEFAULT_PLATFORM=linux/arm64
      # CasaOS-specific optimizations
      - JELLYFIN_FFmpeg__probesize=50000000
      - JELLYFIN_FFmpeg__analyzeduration=50000000
    volumes:
      # CasaOS standard paths
      - /DATA/AppData/jellyfin/config:/config
      - /DATA/AppData/jellyfin/cache:/cache
      - /DATA/Media:/media:ro
      # Plugin-specific volumes
      - /DATA/AppData/jellyfin/plugins:/config/data/plugins
      - /DATA/AppData/jellyfin/upscaler-cache:/config/data/upscaler-cache
    ports:
      - "8096:8096"
      - "8920:8920" # HTTPS (optional)
    devices:
      # Hardware acceleration for supported devices
      - /dev/dri:/dev/dri # Intel/AMD GPU
      # Uncomment for Raspberry Pi GPU (if available)
      # - /dev/vchiq:/dev/vchiq
      # - /dev/vcsm:/dev/vcsm
    restart: unless-stopped
    # CasaOS networking - use host mode for better plugin catalog access
    network_mode: host
    # Resource limits for ARM64/Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # CasaOS-specific labels
    labels:
      - "casaos.name=Jellyfin AI Upscaler"
      - "casaos.description=Jellyfin with AI Upscaler Plugin v1.3.6.1"
      - "casaos.category=Media Server"
      - "casaos.port=8096"
      - "casaos.url=http://localhost:8096"
      - "casaos.author=Kuschel-code"
      - "casaos.version=1.3.6.1"
      - "casaos.arm64=true"
      - "casaos.raspberry-pi=true"
      - "casaos.zimaboard=true"

  # Optional: Watchtower for auto-updates (CasaOS compatible)
  watchtower:
    image: containrrr/watchtower:latest
    container_name: jellyfin-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CONTAINERS_TO_WATCH=jellyfin-ai-upscaler
      - WATCHTOWER_POLL_INTERVAL=86400 # 24 hours
    restart: unless-stopped

# CasaOS-specific networks (optional)
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16